lane :build_ipa_trollstore do
  gym(
    project: "Code.xcodeproj",   # اسم مشروعك
    scheme: "Code App",          # اسم الـ Scheme الخاص بك
    configuration: "Release",    # يمكنك استخدام Debug إذا أردت
    export_method: "development", # TrollStore لا يتطلب توقيعًا
    output_directory: "./build", # المكان الذي سيوضع فيه ملف IPA
    output_name: "MyApp-TrollStore.ipa" # اسم ملف IPA الناتج
  )
end
