name: Build CodeApp IPA for TrollStore

on: 
  workflow_dispatch: # يسمح بتشغيله يدويًا من GitHub Actions

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # استنساخ المستودعات الفرعية إن وجدت
          fetch-depth: 0   # يجلب كل الملفات بدون قيود

      - name: List Project Files
        run: ls -R

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install dependencies
        run: |
          brew install ldid
          sudo gem install fastlane

      - name: Build IPA
        run: |
          xcodebuild clean build \
            -project Code.xcodeproj \
            -scheme "Code" \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=""

      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -r build/Release-iphoneos/Code.app Payload/CodeApp.app
          zip -r CodeApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: CodeApp-IPA
          path: CodeApp.ipa
          if-no-files-found: error
