name: Build CodeApp IPA for TrollStore

on: 
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download missing frameworks
        run: |
          chmod +x downloadFrameworks.sh
          ./downloadFrameworks.sh

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install dependencies
        run: |
          brew install ldid
          sudo gem install fastlane

      - name: Build IPA
        run: |
          xcodebuild clean build \
            -project Code.xcodeproj \
            -scheme "Code App" \
            -sdk iphoneos \  # ✅ إجبار Xcode على بناء إصدار iOS
            -destination generic/platform=iOS \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM="" \
            -verbose

      - name: List Build Directory
        run: ls -R build || echo "No build directory found!"

      - name: Find and Package IPA
        run: |
          mkdir -p Payload
          APP_PATH=$(find build -name "*.app" | head -n 1)
          if [[ -z "$APP_PATH" ]]; then
            echo "Error: No .app file found!"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          cp -r "$APP_PATH" Payload/CodeApp.app
          zip -r CodeApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: CodeApp-IPA
          path: CodeApp.ipa
          if-no-files-found: error
