 - name: List Available Schemes
   run: xcodebuild -list

 - name: Build IPA
   run: |
     xcodebuild clean build \
       -workspace Code.xcworkspace \
       -scheme "Code" \
       -destination generic/platform=iOS \
       CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
